#!/bin/bash

alias pc="proxychains4"
alias ls="ls --color=auto"
alias ll="ls -lha"
alias ra="ranger"
alias sudo="sudo -E"
alias vim="nvim"
alias vimrc="nvim $HOME/.config/nvim/init.vim"
alias dic="ydcv"
alias setProxy="export ALL_PROXY=socks5://127.0.0.1:1080"
alias unsetProxy="unset ALL_PROXY"
